version: '3.9'

services:

  db:
    hostname: db
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    network_mode: bridge
    networks:
      - forall

  custumer:
    hostname: api_customer
    build: 
      context: ./service/customer
    ports:
      - "5001:80"

    networks:
      - forall


  ui:
    build: 
      context: ./app/ui
    ports:
      - "8001:80"
    networks:
      - forall

networks:
  forall:
  